name: ink_voyage
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  image_picker: ^1.0.7
  shared_preferences: ^2.2.3
  http: ^1.2.1
  intl: ^0.19.0
  fl_chart: ^0.66.2
  flutter_svg: ^2.0.10
  
  # Firebase - Compatible versions
  firebase_core: ^3.6.0
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.6.12
  firebase_storage: ^12.3.4
  
  # Utilities
  random_string: ^2.3.1
  fluttertoast: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/icons/
